config/routes.rb
Rails.application.routes.draw do
  
  root to: 'welcome#index'
  
  
  
  resources :welcome 
  resources :mentors
  resources :topics
  resources :podcasts
  resources :sessions
  
  #get '/sessions/:id' => 'sessions#show' 
  
  resources :welcome do 
   get 'session'
   get 'mentors'
   

       

   end 
    
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  
  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mentor.rb
class Mentor < ApplicationRecord
 has_many :sessions
 has_many :topics
end

app/models/podcast.rb
class Podcast < ApplicationRecord
 validates :title, presence: true,
                   length: { minimum: 5 }
end

app/models/session.rb
class Session < ApplicationRecord
 belongs_to :mentor 
 has_many :topics
 
 
 def self.search(search)
  where("name LIKE ?", "%{search}%")
  where("content LIKE ?", "%{search}%")
 end
 
end

app/models/topic.rb
class Topic < ApplicationRecord
 has_many :sessions 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery 
end

app/controllers/mentors_controller.rb
class MentorsController < ApplicationController
 
 def index
  render('mentors/index') 
 end
 
  def show
  render('mentors/index') 
 end
 
 private 
  def mentor_params 
   params.require(:mentor).permit(:name, :bio)
  end
  end 

app/controllers/podcasts_controller.rb
class PodcastsController < ApplicationController
 
 def index
  @podcasts = Podcast.all
 end
 
 def show
  @podcast = Podcast.find(params[:id])
 end 
 
 def new
  @podcast= Podcast.new
 end

 def edit 
  @podcast= Podcast.find(params[:id])
 end

 def create
  @podcast = Podcast.new(podcast_params)
    if @podcast.save
     redirect_to @podcast
    else
     render 'new'
  end
end

 def update 
  @podcast = Podcast.find(params[:id])
  if @podcast.update(podcast_params)
   redirect_to @podcast
  else 
   render 'edit'
  end
 end
 
 def destroy
  @podcast = Podcast.find(params[:id])
  @podcast.destroy

  redirect_to podcasts_path
 end

 private 
  def podcast_params 
   params.require(:podcast).permit(:title, :text)
 end


#A controller is simply a class that is defined 
#to inherit from ApplicationController. 
#It's inside this class that you'll define methods 
#that will become the actions for this controller. 
#These actions will perform CRUD operations 
#on the articles within our system.

end 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
 #belongs_to :mentor 
#end
  layout 'application'


 def index
  @sessions = Session.all
  if params[:search]
   @session = Session.search(params[:search]).order("created_at DESC")
  else
   @session = Session.all.order('created_at DESC')
  end
 end
 
 def show
  @session = Session.find_by_id(params[:id])
 end
 
 def start 
  @session = Session
 end 
 
 def title
 end
 
 def self.search
  
 end 

 private 
  def session_params 
   params.require(:session).permit(:title, :description, :minutes)
  end


#A controller is simply a class that is defined 
#to inherit from ApplicationController. 
#It's inside this class that you'll define methods 
#that will become the actions for this controller. 
#These actions will perform CRUD operations 
#on the articles within our system.
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController


 def index
  @topics = Topic.all
  if params[:search]
   @topic = Topic.search(params[:search]).order("created_at DESC")
  else
   @topic = Topic.all.order('created_at DESC')
  end
 end
 
 def show
  @topic = Topic.find_by_id(params[:id])
 end
 
 def start 
  @topic = Topic
 end 
 
 def title
 end
 
 def self.search
  
 end 

 private 
  def topic_params 
   params.require(:topic).permit(:title, :description, :minutes)
  end


#A controller is simply a class that is defined 
#to inherit from ApplicationController. 
#It's inside this class that you'll define methods 
#that will become the actions for this controller. 
#These actions will perform CRUD operations 
#on the articles within our system.
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout 'application'
  def index
    render('/home')
  end
 
  def home
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/podcasts_helper.rb
module PodcastsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
   "http://www.w3.org/TR/html4/loose.dtd">
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>Mellow | <%= @page_title || 'Mellow' %></title>
    <meta name="author" content="Ariella">
  </head>
  <body>
    <div id="header">
      <h1>Mellow</h1>
    </div>
    
      <%= form_tag(sessions_path, :method => "get", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search sessions" %>
      <%= submit_tag "Search", :name => nil %>
    <% end %>
      <% if @sessions.blank? %>
      <h4>There are no sessions containing the term <%= params[:search] %>.</h4>
    <% end %>


    <div id="main">
      <% if !flash[:notice].blank? %>
      <div class="notice">
        <%= flash[:notice] %>
      </div>
      <% end %>
      <div id="content">
        <%= yield %>
      </div>
    </div>
    <div id="footer">
      <p id="copyright">&copy; mellow.com / AA</p>
    </div>
  </body>
</html>

app/views/mentors/index.html.erb
<ul class="nav nav-tabs" role="tablist">
  <li class="active"><%= link_to 'Mentors', mentors_path %></li>
</ul>

<h1> Mentors</h1>


<%= link_to 'Back', :back %>

app/views/podcasts/_form.html.erb
<%= form_for @podcast do |f| %>
 
  <% if @podcast.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@podcast.errors.count, "error") %> prohibited
        this podcast from being saved:
      </h2>
      <ul>
        <% @podcast.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>


<%#Our edit page looks very similar to the new page; in fact, they both share the same code for displaying the form. Let's remove this duplication by using a view partial. By convention, partial files are prefixed with an underscore.%>

app/views/podcasts/edit.html.erb
<h1>Editing podcast</h1>
 
<%= render 'form' %>
<%= link_to 'Back', podcasts_path %>

app/views/podcasts/index.html.erb
<h1>Listing podcasts</h1>
<%= link_to 'New podcast', new_podcast_path%>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="3"></th>
  </tr>
 

  <% @podcasts.each do |podcast| %>
    <tr>
      <td><%= podcast.title %></td>
      <td><%= podcast.text %></td>
      <td><%= link_to 'Show', podcast_path(podcast) %></td>
      <td><%= link_to 'Edit', edit_podcast_path(podcast) %></td>      
      <td><%= link_to 'Destroy', podcast_path(podcast),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>


    </tr>
  <% end %>
</table>

<%= link_to 'Back', :back %>

app/views/podcasts/new.html.erb
<h1>New Podcast</h1>

<%= render 'form' %>
<%= link_to 'Back', podcasts_path %>

<%# 

When you call form_for, you pass it an identifying object for this form. 
In this case, it's the symbol :podcast. 
This tells the form_for helper what this form is for. 
Inside the block for this method, the FormBuilder object 
- represented by f - is used to build two labels and two text fields,
one each for the title and text of a podcast. 
Finally, a call to submit on the f object will create a submit button for the form.

There's one problem with this form though. If you inspect the HTML that is generated, 
by viewing the source of the page, you will see that 
the action attribute for the form is pointing at /articles/new. 
This is a problem because this route goes to the very page that you're on right at the moment,
and that route should only be used to display the form for a new article.

The form needs to use a different URL in order to go somewhere else. 
This can be done quite simply with the :url option of form_for. 
Typically in Rails, the action that is used for new form submissions like this is called "create", 
and so the form should be pointed to that action.

The articles_path helper tells Rails to point the form to the URI Pattern 
associated with the articles prefix; and the form will (by default) send a POST request to that route. 
This is associated with the create action of the current controller, the PodcastsController.

You now need to create the create action within the ArticlesController for this to work.

When a form is submitted, the fields of the form are sent to Rails as parameters. 
These parameters can then be referenced inside the controller actions, 
typically to perform a particular task.

%>

app/views/podcasts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @podcast.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @podcast.text %>
</p>

<%= link_to 'Edit', edit_podcast_path(@podcast) %>
<%= link_to 'Back', :back %>

app/views/shared/_navigation.html.erb
<!-- app/views/shared/_navigation.html.erb -->

<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Navigate Mellow</a>
    </div>
  </div>
</nav>

app/views/topics/_form.html.erb
<%= form_for @topic do |f| %>
 
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@topic.errors.count, "error") %> prohibited
        this topic from being saved:
      </h2>
      <ul>
        <% @topic.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>


<%#Our edit page looks very similar to the new page; in fact, they both share the same code for displaying the form. Let's remove this duplication by using a view partial. By convention, partial files are prefixed with an underscore.%>

app/views/topics/index.html.erb
<!app/views/topics/index.html.erb
<!DOCTYPE html>

<html>

<head>
	<title>Popular Topics | Mellow</title>	
<link rel="stylesheet" href="topics.css">
</head>

<body id="mellowBody" class="ieRoot_modern lang_en  ">


<div id="" class="view">
	
<section class="stripe stripe--collection padding--left padding--top padding--right">
<ul class="inlineblockList chunk">
<li>
<a href="https://www.mellow.com/" class="link"><span>Home</span></a></li>

<li>
<span>Topics</span>
</li>
</ul>
</section>
<section class="stripe">
<div class="bounds">
<h1 class="text--display3 margin--bottom">Popular topics</h1>
<p>What are you interested in?</p>
</div>
</section>


<section class="stripe">
<div class="bounds">
  <h2 class="margin--bottom"><a class="offsetAnchor" name="arts-culture">Home</a></h2>
  <ul class="gridList gridList--has1 atMedium_gridList--has3 atLarge_gridList--has4">
    <li class="gridList-item">Parents</li>
    <li class="gridList-item">Education</li>
	<li class="gridList-item">Children</li>
    <li class="gridList-item">Holidays </li>
</ul>
</div>
</section>

<section class="stripe">
<div class="bounds">
  <h2 class="margin--bottom">Mindfulness &amp; Meditation</h2>
  <ul class="gridList gridList--has1 atMedium_gridList--has3 atLarge_gridList--has4">
    <li class="gridList-item">Nature</li>
    <li class="gridList-item">Stress</li>
	<li class="gridList-item">Awareness</li>        
	<li class="gridList-item">Mental health</li>

</ul>
</div>
</section>



<section class="stripe">
<div class="bounds">
  <h2 class="margin--bottom"><a class="offsetAnchor" name="career-business">Fitness &amp; Movement</a></h2>
  <ul class="gridList gridList--has1 atMedium_gridList--has3 atLarge_gridList--has4">
    <li class="gridList-item">Body perception</li>
	<li class="gridList-item">Hiking</li>
    <li class="gridList-item">Breathing</li>
    <li class="gridList-item">Imperfections </li>
</ul>
</div>
</section>

<section class="stripe">
<div class="bounds">
  <h2 class="margin--bottom"><a class="offsetAnchor" name="cars-motorcycles">Love &amp; Relationships</a></h2>
  <ul class="gridList gridList--has1 atMedium_gridList--has3 atLarge_gridList--has4">
    <li class="gridList-item">Mindful conversations</li>
    <li class="gridList-item">Letting go</li>
    <li class="gridList-item"><a href="" class="link">Touch</a></li>
    <li class="gridList-item"><a href="" class="link">Apology &amp; acceptance </a></li>
  </ul>
</div>
</section>

<section class="stripe">
<div class="bounds">
  <h2 class="margin--bottom"><a class="offsetAnchor" name="community-environment">Health &amp; Medicine </a></h2>
  <ul class="gridList gridList--has1 atMedium_gridList--has3 atLarge_gridList--has4">
    <li class="gridList-item">Disorders</li>
    <li class="gridList-item">Immunity &amp; disease</li>
    <li class="gridList-item"><a href="" class="link">Terminal illness</a></li>
    <li class="gridList-item"><a href="" class="link">Chronic conditions</a></li>
  </ul>
</div>
</section>

<section class="stripe">
<div class="bounds">
  <h2 class="margin--bottom"><a class="offsetAnchor" name="dancing">Work &amp; Leadership</a></h2>
  <ul class="gridList gridList--has1 atMedium_gridList--has3 atLarge_gridList--has4">
    <li class="gridList-item"><a href="" class="link">Creativity</a></li>
    <li class="gridList-item">Focus</li>
    <li class="gridList-item">Diversity</li>
	<li class="gridList-item"><a href="" class="link">Productivity</a></li>

</ul>
</div>
</section>


</div>


<%= link_to 'Back', :back %>

<footer id="mainFooter">
	<div id="mainFooter-bounds" class="">
		<div class="spreadable atMedium_spreadable--spread"> </div>
		<ul class="inlineblockList chunk bordered">
			<li class="chunk">
				<a href="https://www.mellow.com/help/">Help</a>
			</li>
			<li class="chunk">
				<a href="https://www.mellow.com/about/">About Us</a>
			</li>
		</ul>
		
		<ul class="inlineblockList text--small">
			<li class="text--secondary small">
				&copy; 2016 Mellow
			</li>
			<li class="chunk"><a href="https://www.mellow.com/privacy/">Privacy</a></li>
			<li class="chunk"><a href="https://www.mellow.com/terms/">Terms</a></li>
		</ul>
	</div>
</footer>

	



	</body>
</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mellow</title>
    <%= csrf_meta_tags %>
<link rel="stylesheet" href="index.css"/>

 </head>

  <body>

<ul class="nav nav-tabs" role="tablist">
  <li><%= link_to 'Mentors', mentors_path %></li>
</ul>

<h1>Welcome to Mellow</h1>

<%= link_to 'Sessions', sessions_path, class: 'btn btn-link' %>

<%= link_to 'Mentors', mentors_path %>

<%= link_to 'Topics', topics_path %>

<%= link_to 'Podcasts', podcasts_path %>

</body>
</html>